# Generated by Django 4.2.3 on 2023-07-24 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='meme_images/')),
                ('caption1', models.CharField(max_length=100)),
                ('caption2', models.CharField(blank=True, max_length=100)),
                ('caption3', models.CharField(blank=True, max_length=100)),
                ('font_color1', models.CharField(default='#000000', max_length=7)),
                ('font_color2', models.CharField(default='#000000', max_length=7)),
                ('font_color3', models.CharField(default='#000000', max_length=7)),
                ('background_color1', models.CharField(default='#ffffff', max_length=7)),
                ('background_color2', models.CharField(default='#ffffff', max_length=7)),
                ('background_color3', models.CharField(default='#ffffff', max_length=7)),
                ('caption1_position', models.CharField(default='top', max_length=10)),
                ('caption2_position', models.CharField(default='bottom', max_length=10)),
                ('caption3_position', models.CharField(default='center', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
