# Generated by Django 4.2.3 on 2023-07-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meme_generator_app', '0002_memeimage_generated_meme'),
    ]

    operations = [
        migrations.AddField(
            model_name='memeimage',
            name='crop_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='memeimage',
            name='resize_image',
            field=models.BooleanField(default=False),
        ),
    ]
